### ISSUE TITLE
I can't run it

### ISSUE THREAD

**Issue by RocketLauncher21** [Bob74/iFruitAddon2#7]
I tried to use this with a mod for Cayo Perico heist in SP but it keeps giving an error. Here is the log:

```
[18:22:44] [DEBUG] Instantiating script iFruitAddon2.iFruitAddon2 ...
[18:22:44] [INFO] Started script iFruitAddon2.iFruitAddon2.
[18:22:44] [ERROR] Caught fatal unhandled exception:
System.MissingMethodException: Method not found: 'UInt64* SHVDN.NativeFunc.Invoke(UInt64, UInt64*, Int32)'.
   at GTA.Native.Function.Call[T](Hash hash)
   at iFruitAddon2.iFruitAddon2.Initialize(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[18:22:44] [ERROR] The exception was thrown while executing the script iFruitAddon2.iFruitAddon2.
[18:22:44] [WARNING] Aborted script iFruitAddon2.iFruitAddon2.
```

**Comment by Bob74** [comment]
Hi, are you using ScriptHookVDotNet2 or 3?
iFruitAddon2 is only compatible with ScriptHookVDotNet2 atm.

It might also come from an update of ScriptHookVDotNet2, I will check.

**Comment by WindowsShadows** [comment]
I have both installed

**Comment by WindowsShadows** [comment]
It happened with other mods aswell, I will try removing all other mods and running iFruitAddon2 alone and see what happens

**Comment by morpheuslord** [comment]
i am facing the same issue and i am using the DotNet2
